version: "3.8"

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-tools-backend
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - ai-tools-network
    volumes:
      - ./backend:/app
      - /app/__pycache__
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-tools-frontend
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://ai.jarvismedical.asia/api
    restart: unless-stopped
    networks:
      - ai-tools-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-tools-network:
    driver: bridge

volumes:
  backend_data:
  frontend_data:
